
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway


spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: rsr-api-gateway
            client-secret: gs9VfLEeM268VHLrxP0woZ46OzaHnTW6
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/RockSolidRemedies
            jwk-uri: http://localhost:8080/auth/realms/RockSolidRemedies/protocol/openid-connect/certs

  cloud:
    gateway:
      routes:
        - id: client_admin_route
          uri: http://localhost:8082
          predicates:
            - Path=/admin/product/**
          metadata:
            roles: client_admin
        - id: client_user_route
          uri: http://localhost:8082
          predicates:
            - Path=/product/**
          metadata:
            roles: client_user

server:
  port: 8081
